version: 2
jobs:
  build:
    working_directory: ~/@mathieustan/vue-datepicker
    docker:
    - image: circleci/node:12.11.1

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - yarn-packages-v1-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - yarn-packages-v1-

      - run:
          name: run -> install dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: yarn-packages-v1-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}

      # run Lint
      - run:
          name: run -> code lint
          command: yarn lint
      # run Tests
      - run:
          name: run -> code test
          command: yarn test:client

      # Store result
      - store_test_results:
          path: ./tests/junit/
      - store_artifacts:
          path: ./tests/coverage/
          destination: units
